services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER : myuser
      POSTGRES_PASSWORD : mypasswd
      POSTGRES_DB : mydatabase

    ports:
      - "5515:5432"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

